### PR TITLE
Fixes the "swapVol Created But Not Activated" Problem

### LINKED ISSUE #73: [BUG] Automation Creates But Does Not Mount A `swap` Volume
**Describe the bug**

While the AMIgen8 automation is _creating_ a swap-volume (unless explicitly defeated by passing a swapless disk geometry parameter), it's not actually ensuring that the resultant volume is getting mounted.

**Severity**

Moderately Broken (Trivial work-around)

**To Reproduce**
1. Create a new AMI or VM-template
2. Launch an OE from the AMI or VM-template
3. Execute `cat /proc/swaps` and find that no devices are declared, not even the pre-created swap-volume

**Expected behavior**

Executing `cat /proc/swaps` should return the path of the AMIgen-created swap-volume (and appropriate size attributes)

**Deviance Description**

Resultant OE lacks an active swap-extent for its VMS

**Screenshots**

**Additional context**

**Fix Suggestions**

Update build-automation to ensure an appropriate swap-entry for the script-created swap-volume is present in the `/etc/fstab` file.

### PR DESCRIPTION
**Pull request by ferricoxide**
Prior the application of this update, VMs launched from AMIgen8-created templates will look like:

~~~
sh-4.4$ df -PH
Filesystem                    Size  Used Avail Use% Mounted on
devtmpfs                      4.0G     0  4.0G   0% /dev
tmpfs                         4.0G     0  4.0G   0% /dev/shm
tmpfs                         4.0G  488k  4.0G   1% /run
tmpfs                         4.0G     0  4.0G   0% /sys/fs/cgroup
/dev/mapper/RootVG-rootVol    6.5G  6.1G  338M  95% /
tmpfs                         4.0G     0  4.0G   0% /tmp
/dev/mapper/RootVG-homeVol    1.1G   42M  1.1G   4% /home
/dev/mapper/RootVG-varVol     2.2G  1.3G  900M  58% /var
/dev/mapper/RootVG-logVol     9.7G  380M  9.3G   4% /var/log
/dev/mapper/RootVG-auditVol   6.5G   81M  6.4G   2% /var/log/audit
/dev/mapper/RootVG-varTmpVol  2.2G   50M  2.1G   3% /var/tmp
sh-4.4$ cat /proc/swaps
Filename                                Type            Size            Used            Priority
sh-4.4$

~~~

After application of this update, VMs launched from AMIgen8-created templates will look like:

~~~
sh-4.4$ df -PH
Filesystem                    Size  Used Avail Use% Mounted on
devtmpfs                      4.0G     0  4.0G   0% /dev
tmpfs                         4.0G     0  4.0G   0% /dev/shm
tmpfs                         4.0G  451k  4.0G   1% /run
tmpfs                         4.0G     0  4.0G   0% /sys/fs/cgroup
/dev/mapper/RootVG-rootVol    5.4G  2.7G  2.8G  50% /
tmpfs                         4.0G     0  4.0G   0% /tmp
/dev/mapper/RootVG-homeVol    1.1G   42M  1.1G   4% /home
/dev/mapper/RootVG-varVol     2.2G  488M  1.7G  23% /var
/dev/mapper/RootVG-logVol     2.2G   59M  2.1G   3% /var/log
/dev/mapper/RootVG-auditVol   6.5G   79M  6.4G   2% /var/log/audit
/dev/mapper/RootVG-varTmpVol  2.2G   50M  2.1G   3% /var/tmp
sh-4.4$ cat /proc/swaps
Filename                                Type            Size            Used            Priority
/dev/dm-1                               partition       2097148         0               -2
sh-4.4$
~~~

Closes #73

### CODE REVIEW

**Comment by ferricoxide** [comment]
go codebuild go

File: PostBuild.sh [hunk 1]
```diff
@@ -118,6 +119,23 @@ function CreateFstab {
...
    fi
 
+   # Add any swaps to fstab
+   mapfile -t SWAP_DEVS < <( blkid | awk -F: '/TYPE="swap"/{ print $1 }' )
+   for SWAP in "${SWAP_DEVS[@]}"
+   do
+       if [[ $( grep -q "$( readlink -f "${SWAP}" )" /proc/swaps )$? -eq 0 ]]
+       then
+          err_exit "${SWAP} is already a mounted swap-dev. Skipping" NONE
+          break
```
Comment (lorengordon) [inline PostBuild.sh:129]: I kinda always forget, but just wanted to check if `break` or `continue` would be the appropriate syntax to "skip" this one while still processing the rest?

**Review by lorengordon — APPROVED** [review]
